version: '3.6'
services:
  postgres:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "avoid-hightail-chef-schist"
  graphql-engine:
    image: hasura/graphql-engine:v2.10.1.cli-migrations-v3
    depends_on:
      - postgres
    ports:
      - "7070:7070"
    environment:
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_SERVER_PORT: 7070
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:avoid-hightail-chef-schist@postgres:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "true" to enable console, but be aware that then the migrations/metadata are not written to disc
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,webhook-log,websocket-log,query-log,livequery-poller-log,action-handler-log,data-connector-log # all allowed log-types
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ADMIN_SECRET: "gimcrack-chief-ohmmeter-wurst"
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: "false"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"integrationTestJWTSecret_integrationTestJWTSecret"}'